package com.pax.eemv.enums;

public enum ETransResult {
    ONLINE_APPROVED,
    ONLINE_DENIED,
    ONLINE_FAILED,
    OFFLINE_APPROVED,
    OFFLINE_DENIED,
    ONLINE_CARD_DENIED,
    ABORT_TERMINATED,
    ARQC,
    SIMPLE_FLOW_END,
    CLSS_OC_A,
    CLSS_OC_APPROVED,
    CLSS_OC_B,
    CLSS_OC_C,
    CLSS_OC_CONFIRM_CODE_VER,
    CLSS_OC_D,
    CLSS_OC_DECLINED,
    CLSS_OC_END_APPLICATION,
    CLSS_OC_NA,
    CLSS_OC_NO_CVM,
    CLSS_OC_OBTAIN_SIGNATURE,
    CLSS_OC_ONLINE_PIN,
    CLSS_OC_ONLINE_REQUEST,
    CLSS_OC_SELECT_NEXT,
    CLSS_OC_TRY_AGAIN,
    CLSS_OC_TRY_ANOTHER_INTERFACE,
    OFFLINE_APPROVED_NEED_CHK_REVERSE,
    CLSS_OC_REFER_CONSUMER_DEVICE,
}

/* Location:           E:\Linhb\projects\Android\PaxEEmv_V1.00.00_20170401\lib\PaxEEmv_V1.00.00_20170401.jar
 * Qualified Name:     com.pax.eemv.enums.ETransResult
 * JD-Core Version:    0.6.0
 */